version: "3"
services:
  # Web service layer
  nginx:
    image: nginx:1.13
    volumes:
      - "./:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "85:85"
    depends_on:
      - php
    networks:
      - "networks-php-general"

  # Application service layer
  php:
    build:
      context: ./docker/php
    volumes:
      - ".:/var/www/html"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=123.456
      - ENVIRONMENT=DOCKER
      - DEV_DB_DRIVER=mysql
      - DEV_DB_HOST=mysql
      - DEV_DB_PORT=3306
      - DEV_DB_DATABASE=cooper_leite
    networks:
      - "networks-php-general"
  # Data persistence service layer
  mysql:
    image: mysql:5.7.20
    volumes:
      - "db_data3:/var/lib/mysql"
      - "./docker/db:/docker-entrypoint-initdb.d"
    ports:
      - "3308:3306"
    networks:
      - "networks-php-general"
    environment:
      - MYSQL_ROOT_PASSWORD=123.456
networks:
  networks-php-general:
    driver: "bridge"
    
volumes:
  db_data3: 