load_module modules/ngx_otel_module.so;

user nginx;
worker_processes 1;

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Map trace parent sampled flags to W3C compliance format
    map $otel_parent_sampled $trace_flags {
        default "00";
        "1"     "01";
    }

    # OpenTelemetry Exporter configuration
    otel_exporter {
        endpoint otel-collector:4317;
    }

    otel_service_name nginx-loadbalancer;
    otel_trace on;
    otel_trace_context propagate;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;

    keepalive_timeout 65;

    upstream php_backend {
        server php1:9000;
        server php2:9000;
    }
   
    server {
        listen   85;
        server_name localhost;

        # root directive should be global
        root   /var/www/html;
        index  index.php;
        location / {
#             try_files $uri $uri/ /index.php?request=$args;
#            try_files $uri /index.php;
            try_files $uri /index.php?request=$uri;
#           try_files $uri public/index.php?request=$uri;
        }
                   

        location ~ \.php$ {
            try_files $uri =404;
            include /etc/nginx/fastcgi_params;
            fastcgi_pass    php_backend;
            fastcgi_index   index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            # Propagate the trace context to FastCGI/PHP-FPM
            fastcgi_param HTTP_TRACEPARENT "00-$otel_trace_id-$otel_span_id-$trace_flags";
        }
    }
    
}
