name: Pipeline
on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    name: Testes Automatizados
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0", "8.1"]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mysql

      - name: checkout
        uses: actions/checkout@v2

      - name: Composer Install
        run: |
          composer install --no-progress -o --no-ansi --no-interaction
    
      - name: Rodando PHPUnit
        run: |
          composer test