name: Pipeline
on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    name: Testes Automatizados
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0", "8.1"]

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mysql, pdo_mysql
          ini-values: apc.enable_cli = 1
          coverage: pcov

      - name: checkout
        uses: actions/checkout@v2

      - name: Composer Install
        run: |
          composer install --no-progress -o --no-ansi --no-interaction
    
      - name: Rodando PHPUnit
        run: |
          if [[ ${{ matrix.php-version }} == '8.0' ]]; then
            export CODECOVERAGE=1
            vendor/bin/phpunit --stderr --verbose --coverage-clover=coverage.xml
          else
            vendor/bin/phpunit -c phpunit.xml.dist --stderr
          fi
          
      - name: Code Coverage Report
        if: matrix.php-version == '8.0' 
        uses: codecov/codecov-action@v1

      - name: SonarCloud Scan
        if: matrix.php-version == '8.0'
        uses: SonarSource/sonarcloud-github-action@master
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  mess-detector:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1
        with:
          php_version: 8.1
          path: src/
          output: text
          ruleset: test/phpmd/ruleset.xml