name: 2 Deploy Site on push
on:
  push:
    branches:
      - master
      - develop
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
     
    steps:
    - name: Get the latest code
      uses: actions/checkout@v3.5.3
      with:
          php-version: '7.4'
    - name: Install Dependencies
      run: | 
          composer update
          
    - name: config enviroment
      run: |
        echo '<?php 
        $_ENV["ENVIRONMENT"] = "${{ vars.ENVIRONMENT }}";
        $_ENV["DB_DRIVER"] = "${{ vars.DB_DRIVER }}";
        $_ENV["DB_HOST"] = "${{ secrets.DB_HOST }}";
        $_ENV["DB_PORT"] = "${{ secrets.DB_PORT }}";
        $_ENV["DB_DATABASE"] = "${{ secrets.DB_DATABASE }}";
        $_ENV["MYSQL_USER"] = "${{ secrets.MYSQL_USER }}";
        $_ENV["MYSQL_PASS"] = "${{ secrets.MYSQL_PASS }}";
        ?>' > ./src/env.php
                      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.CPL_SERVER_FTP}}
        username: ${{ secrets.CPL_USER_FTP}}
        password: ${{ secrets.CPL_PASS_FTP}}
        server-dir: ./public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/tests*
          **/tests/**
